"""Generate homogeneous `rows x cols` grids of tpu_like cores, and a matching mapping.

The layout follows `stream/inputs/examples/hardware/tpu_like_quad_core.yaml`:

- compute cores `0 .. rows*cols-1` in row-major order, each joined to its 4-neighbours by a 2-D mesh link;
- one shared SIMD core (`rows*cols`), linked to every compute core, for the elementwise ops (residual Add,
  Softmax) a systolic core does not run;
- the off-chip DRAM controller (`rows*cols + 1`);
- a bus joining every core, the DRAM included.

The YAML references core files by name, which the accelerator parser resolves against `cores/` next to the
accelerator file, so write it into `stream/inputs/examples/hardware/` (the default).
"""

import os
from typing import Any

import yaml

HARDWARE_DIR = os.path.join(os.path.dirname(__file__), "..", "..", "inputs", "examples", "hardware")
MAPPING_DIR = os.path.join(os.path.dirname(__file__), "..", "..", "inputs", "examples", "mapping")

LINK_BANDWIDTH = 32
BUS_BANDWIDTH = 128


def grid_name(rows: int, cols: int) -> str:
    return f"tpu_like_grid_{rows}x{cols}"


def tpu_grid_dict(rows: int, cols: int) -> dict[str, Any]:
    nb_compute = rows * cols
    simd_id, offchip_id = nb_compute, nb_compute + 1
    cores: dict[int, str] = dict.fromkeys(range(nb_compute), "tpu_like.yaml")
    cores[simd_id] = "simd.yaml"
    cores[offchip_id] = "offchip.yaml"

    links: list[dict[str, Any]] = []
    for row in range(rows):
        for col in range(cols):
            core_id = row * cols + col
            if col + 1 < cols:
                links.append({"type": "link", "cores": [core_id, core_id + 1], "bandwidth": LINK_BANDWIDTH})
            if row + 1 < rows:
                links.append({"type": "link", "cores": [core_id, core_id + cols], "bandwidth": LINK_BANDWIDTH})
    links += [
        {"type": "link", "cores": [core_id, simd_id], "bandwidth": LINK_BANDWIDTH} for core_id in range(nb_compute)
    ]
    bus = {"type": "bus", "cores": list(range(nb_compute + 2)), "bandwidth": BUS_BANDWIDTH}

    return {
        "name": grid_name(rows, cols),
        "cores": cores,
        "offchip_core_id": offchip_id,
        "unit_energy_cost": 0,
        "core_connectivity": [*links, bus],
    }


def grid_mapping(rows: int, cols: int) -> list[dict[str, Any]]:
    """Compute ops may land on any grid core, with the inter-core split left to the tiling search (`K, *`);
    Add and Softmax go to the SIMD core."""
    compute_cores = list(range(rows * cols))
    simd_id = rows * cols

    def entry(name: str, cores: list[int], intra: str, inter: str) -> dict[str, Any]:
        return {"name": name, "core_allocation": cores, "intra_core_tiling": [intra], "inter_core_tiling": [inter]}

    return [
        entry("default", compute_cores, "D, all", "K, *"),
        entry("Conv", compute_cores, "OY, all", "K, *"),
        entry("Gemm", compute_cores, "D, all", "K, *"),
        entry("MatMul", compute_cores, "D, all", "K, *"),
        entry("Softmax", [simd_id], "D, all", "H, 1"),
        entry("Add", [simd_id], "D, all", "H, 1"),
    ]


def write_tpu_grid(
    rows: int, cols: int, hardware_dir: str = HARDWARE_DIR, mapping_dir: str = MAPPING_DIR
) -> tuple[str, str]:
    """Write the grid accelerator and its mapping. Returns `(hardware_path, mapping_path)`."""
    name = grid_name(rows, cols)
    hardware_path = os.path.normpath(os.path.join(hardware_dir, f"{name}.yaml"))
    mapping_path = os.path.normpath(os.path.join(mapping_dir, f"{name}.yaml"))
    with open(hardware_path, "w") as f:
        f.write(f"# Generated by stream/hardware/architecture/grid_generator.py: {rows}x{cols} tpu_like mesh.\n")
        yaml.safe_dump(tpu_grid_dict(rows, cols), f, sort_keys=False)
    with open(mapping_path, "w") as f:
        f.write(f"# Generated by stream/hardware/architecture/grid_generator.py for {name}.\n")
        yaml.safe_dump(grid_mapping(rows, cols), f, sort_keys=False)
    return hardware_path, mapping_path


if __name__ == "__main__":
    for size in (2, 4):
        print(*write_tpu_grid(size, size))
