"""One self-contained page for browsing an exploration's Pareto front and the hardware each point implies.

The PNGs in `hardware_graph` answer "what does design N look like"; this answers "which design should I care
about, and what does *that* one look like" -- you pick a point off the trade-off scatter and its topology is
drawn beside it. For a rolled search the comparison is the whole point, so two designs can be pinned side by
side with the edges that the fold added or removed highlighted.

Deliberately dependency-free. The data is inlined into the page rather than fetched from the sibling JSON,
because these artifacts get opened straight off disk (`file://`, over SSH, out of a cluster output directory)
where a `fetch()` of a neighbouring file is blocked by CORS. The scatter and the graph are hand-built SVG: no
charting library to pin, no build step, and the node positions come from `layout_positions`, so the page and
the PNGs place the same cores in the same spots.
"""

import json
import logging
import os
from typing import Any

from stream.visualization.hardware_graph import HardwareTopology, layout_positions

logger = logging.getLogger(__name__)

_TEMPLATE = """<!-- Generated by stream.visualization.topology_report -->
<title>__TITLE__</title>
<style>
  :root {
    color-scheme: light dark;
    --bg: #fbfbfa; --panel: #ffffff; --ink: #1a1a18; --muted: #6b6b66; --line: #dcdcd6;
    --accent: #3b6ea5; --accent-2: #b4632f; --dominated: #c9c9c3;
    --added: #2e7d4f; --removed: #b23b3b; --offchip: #8d8d86; --bus: #a9a9a2;
  }
  @media (prefers-color-scheme: dark) {
    :root {
      --bg: #161715; --panel: #1e201d; --ink: #ececE6; --muted: #9d9d95; --line: #33352f;
      --accent: #7aa9d8; --accent-2: #e0955c; --dominated: #4a4c46;
      --added: #6bbd8c; --removed: #e07a7a; --offchip: #7d7f78; --bus: #5f625a;
    }
  }
  * { box-sizing: border-box; }
  body { background: var(--bg); color: var(--ink); font: 14px/1.5 system-ui, -apple-system, sans-serif; }
  .wrap { padding-block: 20px; padding-left: 16px; padding-right: 16px; max-width: 1500px; margin: 0 auto; }
  h1 { font-size: 1.15rem; margin: 0 0 2px; }
  .sub { color: var(--muted); margin: 0 0 16px; font-size: 0.85rem; }
  .bar { display: flex; flex-wrap: wrap; gap: 10px; align-items: center; margin-bottom: 14px; }
  select, button { font: inherit; padding: 5px 9px; border: 1px solid var(--line); border-radius: 6px;
                   background: var(--panel); color: var(--ink); cursor: pointer; }
  button:hover, select:hover { border-color: var(--accent); }
  label { color: var(--muted); font-size: 0.85rem; }
  .grid { display: grid; grid-template-columns: minmax(280px, 34%) 1fr; gap: 16px; align-items: start; }
  @media (max-width: 820px) { .grid { grid-template-columns: 1fr; } }
  .card { background: var(--panel); border: 1px solid var(--line); border-radius: 10px; padding: 12px; }
  .card h2 { font-size: 0.8rem; text-transform: uppercase; letter-spacing: 0.06em; color: var(--muted);
             margin: 0 0 8px; font-weight: 600; }
  svg { width: 100%; height: auto; display: block; }
  .pt { cursor: pointer; }
  .pt:focus { outline: 2px solid var(--accent); outline-offset: 2px; }
  table { border-collapse: collapse; width: 100%; font-size: 0.82rem; margin-top: 10px; }
  th, td { text-align: left; padding: 3px 6px; border-bottom: 1px solid var(--line); }
  th { color: var(--muted); font-weight: 600; }
  .legend { display: flex; flex-wrap: wrap; gap: 12px; font-size: 0.78rem; color: var(--muted); margin-top: 8px; }
  .swatch { display: inline-block; width: 10px; height: 10px; border-radius: 2px; margin-right: 4px;
            vertical-align: middle; border: 1px solid var(--line); }
  .empty { color: var(--muted); padding: 24px; text-align: center; }
</style>

<div class="wrap">
  <h1>__TITLE__</h1>
  <p class="sub" id="summary"></p>

  <div class="bar">
    <label for="axes">Axes</label>
    <select id="axes"></select>
    <label for="design">Design</label>
    <select id="design"></select>
    <button id="prev" aria-label="Previous design">&#8592;</button>
    <button id="next" aria-label="Next design">&#8594;</button>
    <label for="compare">Compare with</label>
    <select id="compare"></select>
  </div>

  <div class="grid">
    <div class="card">
      <h2>Trade-off</h2>
      <svg id="scatter" viewBox="0 0 420 380" role="img" aria-label="Pareto trade-off scatter"></svg>
      <div class="legend">
        <span><span class="swatch" style="background: var(--accent)"></span>unrolled</span>
        <span><span class="swatch" style="background: var(--accent-2)"></span>rolled</span>
        <span><span class="swatch" style="background: var(--dominated)"></span>dominated</span>
      </div>
      <table id="metrics"></table>
    </div>
    <div class="card">
      <h2 id="graph-title">Hardware topology</h2>
      <svg id="graph" viewBox="0 0 900 560" role="img" aria-label="Accelerator topology"></svg>
      <div class="legend" id="graph-legend"></div>
    </div>
  </div>
</div>

<script type="application/json" id="topology-data">__TOPOLOGY_DATA__</script>
<script>
const DATA = JSON.parse(document.getElementById("topology-data").textContent);
const DESIGNS = DATA.designs, MEASURED = DATA.measured || [];
const OBJ = ["latency", "energy", "area"];
const UNITS = DATA.objectives || {};
const PROJECTIONS = [["latency","energy"],["latency","area"],["energy","area"]];
const SVGNS = "http://www.w3.org/2000/svg";

let current = 0, compare = -1, projection = 0;

const el = (tag, attrs, parent) => {
  const node = document.createElementNS(SVGNS, tag);
  for (const k in attrs) node.setAttribute(k, attrs[k]);
  if (parent) parent.appendChild(node);
  return node;
};
const fmt = v => (v === null || v === undefined) ? "?" :
  (Math.abs(v) >= 1e5 || (Math.abs(v) > 0 && Math.abs(v) < 1e-2) ? v.toExponential(3) : (+v.toFixed(3)).toString());
const label = k => k[0].toUpperCase() + k.slice(1) + (UNITS[k] ? " [" + UNITS[k] + "]" : "");

function fillSelects() {
  const axes = document.getElementById("axes");
  PROJECTIONS.forEach(([x, y], i) => axes.add(new Option(label(y) + " vs " + label(x), i)));
  const design = document.getElementById("design"), cmp = document.getElementById("compare");
  cmp.add(new Option("(none)", -1));
  DESIGNS.forEach((d, i) => {
    const text = d.id + " -- " + d.nb_cores + " core(s), " + d.kind;
    design.add(new Option(text, i));
    cmp.add(new Option(text, i));
  });
  document.getElementById("summary").textContent =
    DESIGNS.length + " pareto design(s) (" + DESIGNS.filter(d => d.kind === "rolled").length +
    " rolled), " + MEASURED.length + " schedule(s) measured in total.";
}

function drawScatter() {
  const svg = document.getElementById("scatter");
  svg.textContent = "";
  const [xk, yk] = PROJECTIONS[projection];
  const W = 420, H = 380, pad = { l: 62, r: 14, t: 12, b: 46 };
  const pts = MEASURED.concat(DESIGNS);
  if (!pts.length) return;
  const xs = pts.map(p => p[xk]), ys = pts.map(p => p[yk]);
  const xmin = Math.min(...xs), xmax = Math.max(...xs);
  const ymin = Math.min(...ys), ymax = Math.max(...ys);
  const sx = v => pad.l + (xmax === xmin ? 0.5 : (v - xmin) / (xmax - xmin)) * (W - pad.l - pad.r);
  const sy = v => H - pad.b - (ymax === ymin ? 0.5 : (v - ymin) / (ymax - ymin)) * (H - pad.t - pad.b);

  const axisAttrs = { stroke: "currentColor", "stroke-opacity": .35 };
  el("line", Object.assign({ x1: pad.l, y1: H - pad.b, x2: W - pad.r, y2: H - pad.b }, axisAttrs), svg);
  el("line", Object.assign({ x1: pad.l, y1: pad.t, x2: pad.l, y2: H - pad.b }, axisAttrs), svg);
  const labAttrs = { "text-anchor": "middle", "font-size": 11, fill: "currentColor", "fill-opacity": .7 };
  const midY = (pad.t + H - pad.b) / 2;
  const xlab = el("text", Object.assign({ x: (pad.l + W - pad.r) / 2, y: H - 12 }, labAttrs), svg);
  xlab.textContent = label(xk);
  const ylab = el("text", Object.assign(
    { x: 14, y: midY, transform: "rotate(-90 14 " + midY + ")" }, labAttrs), svg);
  ylab.textContent = label(yk);

  const paretoIds = new Set(DESIGNS.map(d => d.id));
  MEASURED.filter(m => !paretoIds.has(m.id)).forEach(m =>
    el("circle", { cx: sx(m[xk]), cy: sy(m[yk]), r: 3, fill: "var(--dominated)" }, svg));

  DESIGNS.forEach((d, i) => {
    const g = el("g", { class: "pt", tabindex: 0, role: "button" }, svg);
    const fill = d.kind === "rolled" ? "var(--accent-2)" : "var(--accent)";
    const selected = i === current, pinned = i === compare;
    el("circle", {
      cx: sx(d[xk]), cy: sy(d[yk]), r: selected ? 7 : (pinned ? 6 : 4.5), fill: fill,
      stroke: selected ? "currentColor" : (pinned ? "var(--muted)" : "none"), "stroke-width": selected ? 2 : 1.5,
    }, g);
    const t = el("title", {}, g);
    t.textContent = d.id + "\\n" + OBJ.map(k => label(k) + ": " + fmt(d[k])).join("\\n") +
                    "\\ncores: " + d.nb_cores;
    const pick = () => { current = i; render(); };
    g.addEventListener("click", pick);
    g.addEventListener("keydown", e => {
      if (e.key === "Enter" || e.key === " ") { e.preventDefault(); pick(); }
    });
  });
}

function drawMetrics() {
  const table = document.getElementById("metrics");
  const d = DESIGNS[current], c = compare >= 0 ? DESIGNS[compare] : null;
  const rows = [["cores", d.nb_cores, c ? c.nb_cores : null],
                ["kind", d.kind, c ? c.kind : null]]
    .concat(OBJ.map(k => [label(k), fmt(d[k]), c ? fmt(c[k]) : null]));
  let html = "<tr><th>Metric</th><th>" + d.id + "</th>" + (c ? "<th>" + c.id + "</th>" : "") + "</tr>";
  for (const [name, a, b] of rows) {
    html += "<tr><td>" + name + "</td><td>" + a + "</td>" + (c ? "<td>" + b + "</td>" : "") + "</tr>";
  }
  table.innerHTML = html;
}

function edgeKey(e) { return [String(e.source), String(e.target)].sort().join("~"); }

function drawGraph() {
  const svg = document.getElementById("graph");
  svg.textContent = "";
  const d = DESIGNS[current], other = compare >= 0 ? DESIGNS[compare] : null;
  document.getElementById("graph-title").textContent =
    "Hardware topology -- " + d.id + (other ? "  (vs " + other.id + ")" : "");

  const nodes = d.cores, edges = d.edges;
  if (!nodes.length) { svg.innerHTML = '<text x="20" y="30" fill="currentColor">no cores</text>'; return; }
  const W = 900, H = 560, pad = 70;
  const xs = nodes.map(n => n.x), ys = nodes.map(n => n.y);
  const xmin = Math.min(...xs), xmax = Math.max(...xs), ymin = Math.min(...ys), ymax = Math.max(...ys);
  const sx = v => pad + (xmax === xmin ? 0.5 : (v - xmin) / (xmax - xmin)) * (W - 2 * pad);
  const sy = v => H - pad - (ymax === ymin ? 0.5 : (v - ymin) / (ymax - ymin)) * (H - 2 * pad);
  const pos = {}; nodes.forEach(n => pos[String(n.id)] = [sx(n.x), sy(n.y)]);

  const otherKeys = other ? new Set(other.edges.map(edgeKey)) : null;
  const maxBw = Math.max(...edges.map(e => e.bandwidth), 1);

  edges.forEach(e => {
    const a = pos[String(e.source)], b = pos[String(e.target)];
    if (!a || !b) return;
    let stroke = e.kind === "bus" ? "var(--bus)" : "currentColor";
    let width = 1 + 4 * Math.log1p(e.bandwidth) / Math.log1p(maxBw);
    if (otherKeys && e.kind === "link" && !otherKeys.has(edgeKey(e))) stroke = "var(--added)";
    const line = el("line", {
      x1: a[0], y1: a[1], x2: b[0], y2: b[1], stroke: stroke, "stroke-width": width,
      "stroke-opacity": e.kind === "bus" ? .65 : .85,
    }, svg);
    if (e.kind === "bus") line.setAttribute("stroke-dasharray", "6 4");
    const t = el("title", {}, line);
    t.textContent = e.source + " <-> " + e.target + "  bandwidth " + fmt(e.bandwidth);
  });

  // Links the compared design has and this one does not: drawn faintly, so a fold's removals are visible.
  if (other) {
    const mine = new Set(edges.map(edgeKey));
    other.edges.filter(e => e.kind === "link" && !mine.has(edgeKey(e))).forEach(e => {
      const a = pos[String(e.source)], b = pos[String(e.target)];
      if (!a || !b) return;
      el("line", { x1: a[0], y1: a[1], x2: b[0], y2: b[1], stroke: "var(--removed)",
                   "stroke-width": 1.5, "stroke-dasharray": "3 5", "stroke-opacity": .8 }, svg);
    });
  }

  nodes.forEach(n => {
    const [x, y] = pos[String(n.id)];
    const g = el("g", {}, svg);
    const fill = n.kind === "offchip" ? "var(--offchip)" : (n.kind === "bus" ? "var(--bus)" : "var(--panel)");
    if (n.kind === "compute") {
      el("circle", { cx: x, cy: y, r: 30, fill: fill, stroke: "var(--accent)", "stroke-width": 2 }, g);
    } else if (n.kind === "offchip") {
      el("rect", { x: x - 30, y: y - 22, width: 60, height: 44, rx: 5, fill: fill,
                   stroke: "currentColor", "stroke-width": 1.5 }, g);
    } else {
      const pts = [[x, y - 26], [x + 34, y], [x, y + 26], [x - 34, y]];
      el("polygon", { points: pts.map(p => p.join(",")).join(" "),
                      fill: fill, stroke: "currentColor", "stroke-width": 1.5 }, g);
    }
    (n.label || "").split("\\n").forEach((line, i, all) => {
      const text = el("text", { x: x, y: y + (i - (all.length - 1) / 2) * 11 + 3.5,
                                "text-anchor": "middle", "font-size": 9, fill: "currentColor" }, g);
      text.textContent = line;
    });
    const t = el("title", {}, g);
    t.textContent = [
      "core " + n.id + " (" + n.kind + ")",
      n.design_key ? "design " + n.design_key : null,
      n.area !== null && n.area !== undefined ? "area " + fmt(n.area) : null,
      n.memory_bits ? "memory " + fmt(n.memory_bits) + " bit" : null,
      (n.layers || []).length ? "layers: " + n.layers.map(l => l.name).join(", ") : null,
    ].filter(Boolean).join("\\n");
  });

  document.getElementById("graph-legend").innerHTML =
    '<span><span class="swatch" style="background: var(--panel); border-color: var(--accent)"></span>' +
    'compute core</span>' +
    '<span><span class="swatch" style="background: var(--offchip)"></span>offchip</span>' +
    '<span><span class="swatch" style="background: var(--bus)"></span>bus (one shared link)</span>' +
    (other
      ? '<span><span class="swatch" style="background: var(--added)"></span>link only here</span>' +
        '<span><span class="swatch" style="background: var(--removed)"></span>only in ' + other.id + '</span>'
      : "");
}

function render() {
  document.getElementById("design").value = current;
  document.getElementById("compare").value = compare;
  document.getElementById("axes").value = projection;
  drawScatter(); drawMetrics(); drawGraph();
}

fillSelects();
document.getElementById("design").addEventListener("change", e => { current = +e.target.value; render(); });
document.getElementById("compare").addEventListener("change", e => { compare = +e.target.value; render(); });
document.getElementById("axes").addEventListener("change", e => { projection = +e.target.value; render(); });
const step = delta => { current = (current + delta + DESIGNS.length) % DESIGNS.length; render(); };
document.getElementById("prev").addEventListener("click", () => step(-1));
document.getElementById("next").addEventListener("click", () => step(1));
document.addEventListener("keydown", e => {
  if (e.target.tagName === "SELECT") return;
  if (e.key === "ArrowLeft") step(-1);
  if (e.key === "ArrowRight") step(1);
});
render();
</script>
"""


def design_payload(record: dict[str, Any], topology: HardwareTopology) -> dict[str, Any]:
    """One design as plain JSON: its metrics, and its topology with laid-out node positions.

    Positions are computed here, with the same `layout_positions` the PNGs use, so flipping between the page
    and a saved figure doesn't rearrange the cores."""
    positions = layout_positions(topology)
    cores = []
    for node in topology.nodes:
        x, y = positions.get(node.id, (0.0, 0.0))
        cores.append({**node.to_dict(), "x": float(x), "y": float(y)})
    return {
        "id": record["id"],
        "kind": record.get("kind", "unrolled"),
        "source_id": record.get("source_id"),
        "nb_cores": record.get("nb_cores"),
        "latency": record["latency"],
        "energy": record["energy"],
        "area": record["area"],
        "cores": cores,
        "edges": [edge.to_dict() for edge in topology.edges],
    }


def write_topology_report(
    designs: list[dict[str, Any]],
    html_path: str,
    *,
    json_path: str | None = None,
    title: str = "Stream schedule exploration",
    measured: list[dict[str, Any]] | None = None,
) -> None:
    """Write the interactive page (and, optionally, the same data as a standalone JSON for scripting)."""
    payload = {
        "schema": 1,
        # `Core.get_area()` mixes the operational array's unit area with CACTI mm^2, so it carries no single
        # physical unit -- the same caveat the trade-off figure's axis label makes.
        "objectives": {"latency": "cycles", "energy": "pJ", "area": "a.u."},
        "designs": designs,
        "measured": [
            {
                "id": record["id"],
                "kind": record.get("kind", "unrolled"),
                "latency": record["latency"],
                "energy": record["energy"],
                "area": record["area"],
            }
            for record in (measured or [])
        ],
    }
    encoded = json.dumps(payload).replace("</", "<\\/")
    # Plain replacement, never `str.format`/f-string: the template is full of CSS and JS braces.
    html = _TEMPLATE.replace("__TOPOLOGY_DATA__", encoded).replace("__TITLE__", title)
    os.makedirs(os.path.dirname(html_path) or ".", exist_ok=True)
    with open(html_path, "w", encoding="utf-8") as handle:
        handle.write(html)
    if json_path:
        with open(json_path, "w", encoding="utf-8") as handle:
            json.dump(payload, handle, indent=1)
    logger.info(f"Saved interactive topology report for {len(designs)} design(s) to {html_path}.")
